os: linux
dist: xenial
language: php

php: 7.4

git:
  depth: 1

env:
  - NODE_VERSION="12.16.1"

before_install:
  - nvm install $NODE_VERSION
jobs:
  include:
    - script: make ci

cache:
  directories:
    - $HOME/.composer/cache