os: linux
dist: xenial
language: php
php: 7.4

git:
  depth: 1

cache:
  yarn: true
  directories:
    - node_modules
    - $HOME/.composer/cache

install:
  - nvm install

jobs:
  include:
    - script: make ci
